spring:
  application:
    name: files

files:
  timer:
    # 1 hour
    delete-empty-directories: 3600000

    # 1 hour
    delete-small-files: 3600000

    # 1 hour
    copy-files: 3600000

    # 1.5 hours
    duplicate-media-basic: 5400000

    # 2 weeks
    duplicate-media-advance: 1209600000
